spring.application.name=smart-campus-backend
server.port=8081
spring.data.mongodb.uri=mongodb+srv://gpasindu47_db_user:XGnqew9WOPLjByG3@paf.r4zg72y.mongodb.net/?appName=paf
spring.data.mongodb.database=smart_campus_db